default:
  zooKeeper:
    host: "localhost" # ZooKeeper host
    port: 2181 # ZooKeeper port
  server:
    ip: "192.168.50.138"
    startPort: 8000 # Starting port range
    endPort: 9000 # Ending port range
  dataDirectory: "/tmp" # Directory for data files
  memTable:
    schedule: 60 # Memtable flush schedule
    numOfRecords: 4 # Number of records for flush
  compaction:
    schedule: 60 # SSTable compaction schedule
    numOfFiles: 2 # Number of files for compaction

production:
  server:
    ip: "0.0.0.0" # Server IP address for production
    startPort: 8000 # Starting port range
    endPort: 9000 # Ending port range


