global:
  scrape_interval: 15s  # Scrape every 15 seconds

scrape_configs:
  - job_name: CoreCacheNode1
    static_configs:
      - targets: ["$host1"]  # CoreCache Node 1

  - job_name: CoreCacheNode2
    static_configs:
      - targets: ["$host2"]  # CoreCache Node 2
  
  - job_name: CoreCacheNode3
    static_configs:
      - targets: ["$host3"]  # CoreCache Node 2

