global:
  scrape_interval: 15s  # Scrape every 15 seconds

scrape_configs:
  - job_name: CoreCacheNode1
    static_configs:
      - targets: ["192.168.50.138:8536"]  # Replace with the endpoint of the first service

  - job_name: CoreCacheNode2
    static_configs:
      - targets: ["192.168.50.138:8800"]  # Replace with the endpoint of the second service
  
  - job_name: Prometheus
    static_configs:
      - targets: ["localhost:9090"]

  # Optionally, you can add more scrape configurations as needed
