name: Terraform Destroy

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.4  # Specify the Terraform version you need

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Specify the AWS region you are using

      - name: Terraform Init
        run: terraform init -backend-config="bucket=corecache-tf-state" -backend-config="key=tf-state/terraform.tfstate" -backend-config="region=us-east-1"
        working-directory: deployment/aws

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: deployment/aws
